// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-blog-posts.ts
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published blog posts, newest first. Optionally filter by category or a title/excerpt search term.",
  inputSchema: {
    search: z.string().trim().optional().describe("Match against title and excerpt."),
    category: z.string().trim().optional().describe("Exact category name, e.g. 'Security'."),
    limit: z.number().int().min(1).max(50).optional().describe("Max posts to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("blog_posts").select("id, title, excerpt, category, read_time, date, cover_image").order("date", { ascending: false }).limit(limit ?? 10);
    if (category) query = query.eq("category", category);
    if (search) query = query.or(`title.ilike.%${search}%,excerpt.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch the full markdown content and metadata of a single blog post by its id.",
  inputSchema: { id: z2.string().trim().min(1).describe("The blog post id (slug).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("blog_posts").select("id, title, excerpt, content, category, read_time, date, cover_image").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No blog post found with id "${id}".` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/create-blog-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var create_blog_post_default = defineTool3({
  name: "create_blog_post",
  title: "Create blog post",
  description: "Publish a new blog post written in GitHub-flavored markdown. Requires an admin account; non-admins are rejected by database policy.",
  inputSchema: {
    id: z3.string().trim().min(1).describe("URL slug, e.g. 'react-security-best-practices'."),
    title: z3.string().trim().min(1),
    excerpt: z3.string().trim().min(1).describe("Short summary shown in listings and social previews."),
    content: z3.string().trim().min(1).describe("Full post body in GitHub-flavored markdown."),
    category: z3.string().trim().min(1),
    read_time: z3.string().trim().min(1).describe("Human-readable reading time, e.g. '6 min read'."),
    cover_image: z3.string().trim().url().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("blog_posts").insert({ ...input, author_id: ctx.getUserId() }).select("id, title, category, date").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Published "${data.title}" at /blog/${data.id}` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "List portfolio projects",
  description: "List portfolio projects with their status, tech stack, and links, ordered as shown on the site.",
  inputSchema: {
    status: z4.string().trim().optional().describe("Filter by status, e.g. 'live' or 'in-progress'."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max projects to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("projects").select("id, title, description, status, tech, github, demo, display_order").order("display_order", { ascending: true }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/post-comment.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var post_comment_default = defineTool5({
  name: "post_comment",
  title: "Post a comment",
  description: "Add a comment (or a threaded reply) to a blog post as the signed-in user.",
  inputSchema: {
    post_id: z5.string().trim().min(1).describe("The blog post id to comment on."),
    content: z5.string().trim().min(1).max(1e3),
    parent_id: z5.string().trim().uuid().optional().describe("Comment id to reply to.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ post_id, content, parent_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("comments").insert({ post_id, content, parent_id: parent_id ?? null, user_id: ctx.getUserId() }).select("id, post_id, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Comment posted on ${data.post_id}.` }],
      structuredContent: { comment: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "stfnesotidzrpyzbxqbl";
var mcp_default = defineMcp({
  name: "abule-s-tech-hub",
  title: "Abule's Tech Hub",
  version: "0.1.0",
  instructions: "Tools for Abule's Tech Hub, a developer blog and portfolio. Read and search blog posts, read full markdown content, list portfolio projects, publish new posts (admins only), and comment on posts as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_blog_posts_default, get_blog_post_default, create_blog_post_default, list_projects_default, post_comment_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
